### ISSUE TITLE
search: ES reindexing is failing

### ISSUE THREAD

**Issue by cafexpreso** [zenodo/zenodo#1016]
I want to use a different elasticsearh backend, I have issue the following commands to repopulate the new backend and it seems not to be working see the attached celery log
 zenodo index reindex
 zenodo index run -c 4 -d

 zenodo index reindex
/opt/.virtualenv/zenodo/lib/python2.7/site-packages/dojson/contrib/to_marc21/model.py:22: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
Do you really want to reindex all records? [y/N]: y
Sending records to indexing queue ...
Execute "run" command to process the queue!

 zenodo index run -c 4 -d
/opt/.virtualenv/zenodo/lib/python2.7/site-packages/dojson/contrib/to_marc21/model.py:22: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
Starting 4 tasks for indexing records...

[reindex_fails.txt](https://github.com/zenodo/zenodo/files/841299/reindex_fails.txt)

**Comment by cafexpreso** [comment]
Do I have to load again the zenodo fixtures init after reindex?

**Comment by krzysztof** [comment]
Are you pointing to the new ES backend? https://github.com/zenodo/zenodo/blob/master/docker-compose.yml#L57

Also, you will have to init the ES first: https://github.com/zenodo/zenodo/blob/master/scripts/init.sh#L26-L27

**Comment by cafexpreso** [comment]
Hi 
Yes I can confirm I can connect to the new elk instance
I had run the steps you mentioned below find the result


[init index.txt](https://github.com/zenodo/zenodo/files/841372/init.index.txt)

**Comment by krzysztof** [comment]
Something is indexed there already, can you try ``zenodo index destroy --force`` and then init again?

**Comment by cafexpreso** [comment]
Now it is better but still there is a problem showed in celery

[reindex after destroy.txt](https://github.com/zenodo/zenodo/files/841503/reindex.after.destroy.txt)

**Comment by cafexpreso** [comment]
This is the error, does it mean that this record 9ea0672-0c89-4ad1-b596-b8b5e08c774d is corrupted?

How can I check it

`[2017-03-14 09:57:00,988: WARNING/Worker-4] [2017-03-14 09:57:00,988] ERROR in api: Failed to index record a9ea0672-0c89-4ad1-b596-b8b5e08c774d
Traceback (most recent call last):
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/api.py", line 245, in _actionsiter
    yield self._index_action(payload)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/api.py", line 280, in _index_action
    index, doc_type = self.record_to_index(record)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/api.py", line 89, in record_to_index
    return self._record_to_index(record)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/werkzeug/local.py", line 371, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/root/src/zenodo/zenodo/modules/indexer/utils.py", line 44, in record_to_index
    index, doc_type = default_record_to_index(record)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/utils.py", line 76, in default_record_to_index
    index, doc_type = schema_to_index(schema, index_names=index_names)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_search/utils.py", line 49, in schema_to_index
    parts = schema.split('/')
AttributeError: 'NoneType' object has no attribute 'split'
[2017-03-14 09:57:00,988: ERROR/Worker-4] Failed to index record a9ea0672-0c89-4ad1-b596-b8b5e08c774d
Traceback (most recent call last):
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/api.py", line 245, in _actionsiter
    yield self._index_action(payload)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/api.py", line 280, in _index_action
    index, doc_type = self.record_to_index(record)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/api.py", line 89, in record_to_index
    return self._record_to_index(record)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/werkzeug/local.py", line 371, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/root/src/zenodo/zenodo/modules/indexer/utils.py", line 44, in record_to_index
    index, doc_type = default_record_to_index(record)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_indexer/utils.py", line 76, in default_record_to_index
    index, doc_type = schema_to_index(schema, index_names=index_names)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_search/utils.py", line 49, in schema_to_index
    parts = schema.split('/')
AttributeError: 'NoneType' object has no attribute 'split'
`

**Comment by lnielsen** [comment]
Actually the ``scripts/index.sh`` is wrong. It's using ``zenodo index reindex`` which will at best produce the correct result, at worst it will try to index deleted records because it doesn't take the PID delete state into account. The correct would be to run something like:

```
zenodo migration reindex -t recid
zenodo migration reindex -t frdoi
zenodo migration reindex -t od_lic
zenodo migration reindex -t grant
```
