### ISSUE TITLE
DataCiteUnauthorizedError(u'Bad credentials',)

### ISSUE THREAD

**Issue by cafexpreso** [zenodo/zenodo#1019]
Hello,

I am observing this from celery logs is there any special operation to purge or complete this operation?

`<2017-03-14 10:51:48,086: INFO/MainProcess] Task invenio_indexer.tasks.index_record[94efc5d8-7beb-4812-9eee-8f8e5f81001c] succeeded in 0.0561410720038s: None
[2017-03-14 10:57:07,585: INFO/Worker-3] Deleted PID.
[2017-03-14 10:57:08,313: ERROR/Worker-3] Failed to delete in DataCite
Traceback (most recent call last):
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_pidstore/providers/datacite.py", line 178, in delete
    self.api.metadata_delete(self.pid.pid_value)
  File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/datacite/client.py", line 152, in metadata_delete
    raise DataCiteError.factory(r.code, r.data)
DataCiteUnauthorizedError: Bad credentials
[2017-03-14 10:57:08,330: INFO/MainProcess] Received task: zenodo.modules.deposit.tasks.datacite_inactivate[af6d2d06-a939-41c7-95b3-58dfe4982db6] eta:[2017-03-14 15:07:08.317238+00:00]
[2017-03-14 10:57:08,332: INFO/MainProcess] Task zenodo.modules.deposit.tasks.datacite_inactivate[af6d2d06-a939-41c7-95b3-58dfe4982db6] retry: Retry in 600s: DataCiteUnauthorizedError(u'Bad credentials',)>`

**Comment by krzysztof** [comment]
This means that you are unauthorized to get a DOI from DataCite.
Do you need to mint DOIs?

To turn it off you would need to not register this signal: https://github.com/zenodo/zenodo/blob/fb2fb960e2719b062655125d9bcb06d3ac2a70a6/zenodo/modules/deposit/ext.py#L62

**Comment by krzysztof** [comment]
or set this to false: https://github.com/zenodo/zenodo/blob/fb2fb960e2719b062655125d9bcb06d3ac2a70a6/zenodo/modules/deposit/receivers.py#L38

**Comment by cafexpreso** [comment]
How about if the user has its own DOI

**Comment by krzysztof** [comment]
Then they can provide it in the form as usual. This is only if you mint one for them if they don't have one.

In Zenodo we assume the DOI is there (either specified by user, or minted by us). If you don't want to mint yourself, you need to enforce that users provides one on the form.

**Comment by cafexpreso** [comment]
Mint means formatting this

**Comment by cafexpreso** [comment]
Ok the errors disappeared after applying the change suggested.
Thank you!
