### ISSUE TITLE
Internal Server Error when I try to publish a record

### ISSUE THREAD

**Issue by suso2** [zenodo/zenodo#1067]
Steps I followed:

$ cd ~/src/
$ git clone https://github.com/zenodo/zenodo.git
$ cd ~/src/zenodo
$ git checkout master
$ docker-compose build
$ docker-compose up

Now, from a new shell:

$ cd ~/src/zenodo
$ docker-compose run --rm web bash /code/zenodo/scripts/init.sh
$ docker-compose run --rm statsd bash /init.sh
$ docker-compose run --rm web zenodo migration reindex -t od_lic
$ docker-compose run --rm web zenodo index run -d

I did not load the demo records. I can login successfully. The next step is to create a record (a pdf book). I can upload the pdf file, enter the metadata and save it but when I try to publish the record I get an Internal Server Error.

**docker-compose logs:**

es_1 | Caused by: SearchParseException[failed to parse search source [{"from": 0, "size": 10, "query": {"bool": {"filter": [{"query_string": {"query": "communities:zenodo AND access_right:open"}}]}}, "sort": [{"_created": {"order": "desc"}}]}]]; nested: SearchParseException[No mapping found for [_created] in order to sort on];
es_1 | at org.elasticsearch.search.SearchService.parseSource(SearchService.java:855)
es_1 | at org.elasticsearch.search.SearchService.createContext(SearchService.java:654)
es_1 | at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:620)
es_1 | at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:371)
es_1 | at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
es_1 | at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
es_1 | at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
es_1 | at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
es_1 | at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
es_1 | at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
es_1 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
es_1 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
es_1 | at java.lang.Thread.run(Thread.java:745)
es_1 | Caused by: SearchParseException[No mapping found for [_created] in order to sort on]
es_1 | at org.elasticsearch.search.sort.SortParseElement.addSortField(SortParseElement.java:213)
es_1 | at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:187)
es_1 | at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:85)
es_1 | at org.elasticsearch.search.SearchService.parseSource(SearchService.java:838)
es_1 | ... 12 more
es_1 | [2017-04-28 08:07:29,796][DEBUG][action.search ] [Volstagg] [records-records-files-v1.0.0][0], node[n75bxV5WQqytHfLmU52IQw], [P], v[2], s[STARTED], a[id=TpVcTVb6Q_ubup0grG-eIw]: Failed to execute [org.elasticsearch.action.search.SearchRequest@4d6fe9e6] lastShard [true]
es_1 | RemoteTransportException[[Volstagg][172.17.0.3:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"from": 0, "size": 10, "query": {"bool": {"filter": [{"query_string": {"query": "communities:zenodo AND access_right:open"}}]}}, "sort": [{"_created": {"order": "desc"}}]}]]; nested: SearchParseException[No mapping found for [_created] in order to sort on];

Any idea? Thanks in advance

**Comment by suso2** [comment]
Hi. I have just seen that if I create a new community and I put the documents/records on that community, all works fine (no Internal Server Error). If I use the community "Zenodo" I can't publish any record.
How can I show these records on the frontpage?
Thanks
