### ISSUE TITLE
PDF documents not displaying / downloading in Chrome and Firefox browsers on OS X Sierra

### ISSUE THREAD

**Issue by npch** [zenodo/zenodo#1093]
PDF documents stored in Zenodo do not display when using the Chrome and Firefox browsers on OS X Sierra, presenting an "Unexpected server response":

![image](https://cloud.githubusercontent.com/assets/1507151/26247594/871927fe-3c96-11e7-805b-2c28b069509b.png)

When clicking on the Download button I get the error 

```
This page isn’t working
zenodo.org sent an invalid response.
ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
```

Using Safari does not present this problem. 

This was first reported on https://zenodo.org/record/495360#.WR7mNFPyvHf but also appears to be an issue for other PDF documents in Zenodo.

**Comment by lnielsen** [comment]
Fixed yesterday afternoon. It was caused by a fix for an XSS vulnerability that we discovered ourselves during a security review of the code base.

**Comment by suso2** [comment]
I have the same problem using the Zenodo code updated on 30th May.
The first time I created the record all was working but after restarting the docker containers the problems started.
Using Chrome, Microsoft Edge and Firefox on Windows 10 presents the same problem.

Thanks.

<img width="808" alt="zenodo02" src="https://cloud.githubusercontent.com/assets/7069866/26572129/1359b500-4519-11e7-883a-e87655e46dc9.png">

**Comment by suso2** [comment]
<img width="822" alt="001" src="https://cloud.githubusercontent.com/assets/7069866/26603129/10bdb05e-4586-11e7-8b70-57380e579893.png">
<img width="818" alt="002" src="https://cloud.githubusercontent.com/assets/7069866/26603131/10f997e0-4586-11e7-8016-ff81f9166775.png">

Maybe this problem is not caused by the XSS vulnerability. I have created a second version of the record and the second one works. If I try to download the first document I get this message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 185, in __call__
    return self.app(environ, rewriting_start_response)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/wsgi.py", line 659, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1746, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/wrappers.py", line 847, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.5/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/exceptions.py", line 155, in __call__
    response = self.get_response(environ)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/exceptions.py", line 146, in get_response
    return Response(self.get_body(environ), self.code, headers)
  File "/usr/local/lib/python3.5/site-packages/invenio_rest/errors.py", line 90, in get_body
    errors = self.get_errors()
  File "/usr/local/lib/python3.5/site-packages/invenio_rest/errors.py", line 77, in get_errors
    return [e.to_dict() for e in self.errors] if self.errors else None
  File "/usr/local/lib/python3.5/site-packages/invenio_rest/errors.py", line 77, in <listcomp>
    return [e.to_dict() for e in self.errors] if self.errors else None
AttributeError: 'str' object has no attribute 'to_dict'

**Comment by lnielsen** [comment]
Could it be that you removed the other document from disk on your local Zenodo installation?
