### ISSUE TITLE
Issue starting Zenodo using docker-compose

### ISSUE THREAD

**Issue by ThriceGood** [zenodo/zenodo#1362]
Hello,

I've been trying to run Zenodo with docker. I have followed the installation steps:

pull repo,
cd into repo,
docker-compose build
docker-compose up

But I get some errors when the system tries to start up. Any ideas why this might be? Is anyone else getting these errors?

static_1  | tail: unrecognized file system type 0x794c7630 for ‘/var/log/faillog’. please report this to bug-coreutils@gnu.org. reverting to polling
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/bin/zenodo", line 6, in <module>
web_1     |     from pkg_resources import load_entry_point
web_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3144, in <module>
web_1     |     @_call_aside
web_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3128, in _call_aside
web_1     |     f(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3157, in _initialize_master_working_set
web_1     |     working_set = WorkingSet._build_master()
web_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 666, in _build_master
web_1     |     ws.require(__requires__)
web_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
web_1     |     needed = self.resolve(parse_requirements(requirements))
web_1     |   File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 870, in resolve
web_1     |     raise DistributionNotFound(req, requirers)
web_1     | pkg_resources.DistributionNotFound: The 'zenodo' distribution was not found and is required by the application
zenodo_web_1 exited with code 1

flower_1  | [W 171204 12:55:14 control:44] 'stats' inspect method failed
flower_1  | [W 171204 12:55:14 control:44] 'active_queues' inspect method failed
flower_1  | [W 171204 12:55:14 control:44] 'registered' inspect method failed
flower_1  | [W 171204 12:55:14 control:44] 'scheduled' inspect method failed
flower_1  | [W 171204 12:55:14 control:44] 'active' inspect method failed
flower_1  | [W 171204 12:55:14 control:44] 'reserved' inspect method failed
flower_1  | [W 171204 12:55:14 control:44] 'revoked' inspect method failed
flower_1  | [W 171204 12:55:14 control:44] 'conf' inspect method failed
worker_1  | [2017-12-04 12:55:15,278: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Cannot assign requested address..
worker_1  | Trying again in 4.00 seconds...
worker_1  | 
worker_1  | [2017-12-04 12:55:19,286: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Cannot assign requested address..
worker_1  | Trying again in 6.00 seconds...
worker_1  | 
worker_1  | [2017-12-04 12:55:25,298: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Cannot assign requested address..
worker_1  | Trying again in 8.00 seconds...
worker_1  | 
worker_1  | [2017-12-04 12:55:33,312: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Cannot assign requested address..
worker_1  | Trying again in 10.00 seconds...
worker_1  | 
worker_1  | [2017-12-04 12:55:43,327: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: Error 99 connecting to localhost:6379. Cannot assign requested address..
worker_1  | Trying again in 12.00 seconds...

**Comment by rbrink** [comment]
Any updates on this?

**Comment by stain** [comment]
I get a similar error from `worker`:

```
worker_1  | [2018-10-30 14:39:02,030: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
worker_1  | Trying again in 26.00 seconds...
worker_1  | 
worker_1  | [2018-10-30 14:39:28,068: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
worker_1  | Trying again in 28.00 seconds...
```

So it seems the celery worker is not picking up the `INVENIO_BROKER_URL` and wrongly tries to connect to `localhost` - which would be the wrong docker container.

```
stain@biggie:~/src/zenodo$ docker-compose exec worker bash
zenodo@fb5bc69dc907:/code/zenodo$ export | grep mq
declare -x INVENIO_BROKER_URL="amqp://guest:guest@mq:5672//"
```

    
    declare -x INVENIO_BROKER_URL="amqp://guest:guest@mq:5672//"
