### ISSUE TITLE
License field for New Upload does not work

### ISSUE THREAD

**Issue by fmarco76** [zenodo/zenodo#1635]
I have a clean deploy and everything looks Ok but I cannot upload new document because the license field does not get populated. I get the following error:

```
frontend_1  | 172.18.0.12 - - [06/Nov/2018:09:53:05 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
web_1       |     return self.wsgi_app(environ, start_response)
web_1       |   File "/usr/local/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
web_1       |     return self.app(environ, start_response)
web_1       |   File "/usr/local/lib/python3.5/site-packages/werkzeug/wsgi.py", line 826, in __call__
web_1       |     return app(environ, start_response)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
web_1       |     return self.wsgi_app(environ, start_response)
web_1       |   File "/usr/local/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
web_1       |     return self.app(environ, start_response)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
web_1       |     response = self.handle_exception(e)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 273, in error_router
web_1       |     return original_handler(e)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
web_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
web_1       |     reraise(exc_type, exc_value, tb)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
web_1       |     raise value
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
web_1       |     response = self.full_dispatch_request()
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
web_1       |     rv = self.handle_user_exception(e)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 273, in error_router
web_1       |     return original_handler(e)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask_cors/extension.py", line 161, in wrapped_function
web_1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
web_1       |     reraise(exc_type, exc_value, tb)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
web_1       |     raise value
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
web_1       |     rv = self.dispatch_request()
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
web_1       |     return self.view_functions[rule.endpoint](**req.view_args)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
web_1       |     return self.dispatch_request(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 149, in dispatch_request
web_1       |     return meth(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.5/site-packages/invenio_records_rest/views.py", line 820, in get
web_1       |     for resp in response[field]:
web_1       | KeyError: 'text'
web_1       | [pid: 27|app: 0|req: 1579/3370] 172.18.0.11 () {46 vars in 1011 bytes} [Tue Nov  6 09:53:06 2018] GET /api/licenses/_suggest?text=apache => generated 0 bytes in 29 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)
```

I have a full docker based deployment (I have used docker-compose.full.yml)

**Comment by fmarco76** [comment]
The indexing was failing but after several attempt I get the license field work

**Comment by slint** [comment]
Yeah, that's missing from the dev docs, you have to run `zenodo index reindex -t od_lic` and then `zenodo index run` to have the licenses available for searching

**Comment by fmarco76** [comment]
Yes, that are the correct steps. Thanks
