### ISSUE TITLE
Development Installation Error Egg_Info

### ISSUE THREAD

**Issue by JaFro96** [zenodo/zenodo#1636]
We are a student group trying to enhance the zenodo software for similarity calculation. We get the following error during the development installation:

OS: Linux
Use docker for DB, ES, MQ, Cache etc.
Step in the Installation Guide: Development Installation
**(zenodo)$ pip install -r requirements.txt --src ~/src/ --pre --upgrade**

Stacktrace:
`Using cached https://files.pythonhosted.org/packages/c1/2b/ce0abe80c1dcc80fcc3ac7a73f19c9d095592466ca97a530d512cbb4d242/isbnid_fork-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    /home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/dist.py:398: UserWarning: Normalizing \'0.5.3
    \' to \'0.5.3\'
      normalized_version,
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-install-LH5dPP/isbnid-fork/.eggs/autosemver-0.5.3-py2.7.egg
    Searching for dulwich
    Reading https://pypi.org/simple/dulwich/
    Downloading https://files.pythonhosted.org/packages/5d/2a/d2c639a97b5aca864cc1ff834151df0b68fd129f1b95a7068652b777d4cd/dulwich-0.19.7.tar.gz#sha256=1da2f515bfee0f046cd7f1da2929a76d92352780b5c42fac45a3a1f1f910eed9
    Best match: dulwich 0.19.7
    Processing dulwich-0.19.7.tar.gz
    Writing /tmp/easy_install-i3BMw4/dulwich-0.19.7/setup.cfg
    Running dulwich-0.19.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-i3BMw4/dulwich-0.19.7/egg-dist-tmp-1SutNX
    dulwich/_objects.c:21:10: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-LH5dPP/isbnid-fork/setup.py", line 38, in <module>
        'bugtracker_url': 'https://github.com/inspirehep/isbnid/issues'},
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in setup
        _install_setup_requires(attrs)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/__init__.py", line 134, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
        replace_conflicting=replace_conflicting
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1060, in best_match
        return self.obtain(req, installer)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1072, in obtain
        return installer(requirement)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 676, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 702, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 887, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1155, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1143, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-LH5dPP/isbnid-fork/`

**Comment by geekdinazor** [comment]
Install python-dev package via apt install python-dev.

**Comment by yhallowiegeht** [comment]
after installing the development package and following the remaining tutorial, i got the error when trying to access the site after running zenodo run. There is no error in the firefox development console, only the linux console, where zenodo run is executed, shows some weird stuff 
![screenshot from 2018-11-06 15-23-31](https://user-images.githubusercontent.com/38653845/48070500-4749bb00-e1d8-11e8-92e6-31b3c5857f8e.png)

**Comment by geekdinazor** [comment]
We was experienced same issue. Run export FLASK_DEBUG=True  before run. You may want to add that ~/.bashrc for future runs.

**Comment by yhallowiegeht** [comment]
Thanks for the quick help, it works fine now!
