### ISSUE TITLE
PermissionDeniedError while uploading a file

### ISSUE THREAD

**Issue by JaFro96** [zenodo/zenodo#1678]
Hi all, 
I followed the instruction of the Development Installation in [install.rst] and am using __Linux Mint 19 Cinnamon__(https://github.com/zenodo/zenodo/blob/master/INSTALL.rst).
I successfully created a test account and a test community, but I failed while trying to __upload a file__.
![image](https://user-images.githubusercontent.com/38653702/51188830-027c8780-18df-11e9-9672-bd67b7ca01f6.png)

While trying to upload a file, I get the following error: PermissionDeniedError: Unable to _os_makedirs: permission denied

### Stacktrace:
(zenodo) jannis@jannis-Lenovo-E31-80:~/Envs/zenodo$ FLASK_DEBUG=True zenodo run --reload --with-threads
 * Forcing debug mode on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/invenio_oauth2server/ext.py:265: RuntimeWarning: You are overriding the default OAuthlib "URL encoded" set of valid characters. Make sure that the characters defined in oauthlib.common.urlencoded are indeed limitting your needs.
  RuntimeWarning

 * Debugger is active!
 * Debugger PIN: 122-653-222
/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/invenio_oauth2server/ext.py:265: RuntimeWarning: You are overriding the default OAuthlib "URL encoded" set of valid characters. Make sure that the characters defined in oauthlib.common.urlencoded are indeed limitting your needs.
  RuntimeWarning

/home/jannis/Envs/zenodo/local/lib/python2.7/site-packages/werkzeug/local.py:347: DeprecationWarning: Request.is_xhr is deprecated. Given that the X-Requested-With header is not a part of any spec, it is not reliable
  return getattr(self._get_current_object(), name)

127.0.0.1 - - [15/Jan/2019 15:47:05] "GET /deposit/45512 HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2019 15:47:05] "GET /_debug_toolbar/static/css/toolbar.css?0.3017855846729107 HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2019 15:47:06] "GET /static/templates/zenodo_deposit/strapselect.html HTTP/1.1" 404 -
127.0.0.1 - - [15/Jan/2019 15:47:08] "GET /api/communities/?q=&size=7 HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2019 15:47:08] "GET /api/licenses/_suggest?size=10&text=CC-BY-4.0 HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2019 15:47:11] "PUT /api/files/8d514273-3da9-46fa-868d-8f48c4cadab4/schlangenberg_zeitreihe.csv HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_rest/views.py", line 240, in dispatch_request
    *args, **kwargs
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/webargs/core.py", line 449, in wrapper
    return func(*args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/views.py", line 231, in decorate
    return f(bucket=bucket, *args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/views.py", line 288, in decorate
    return f(*args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/views.py", line 796, in put
    return self.create_object(bucket, key)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/views.py", line 531, in create_object
    stream, size=content_length, size_limit=size_limit)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/models.py", line 138, in inner
    return f(self, *args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/models.py", line 124, in inner
    res = f(self, *args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/models.py", line 950, in set_contents
    default_storage_class=self.bucket.default_storage_class,
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/models.py", line 138, in inner
    return f(self, *args, **kwargs)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/models.py", line 778, in set_contents
    size_limit=size_limit, progress_callback=progress_callback))
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/storage/pyfs.py", line 115, in save
    fp = self.open(mode='wb')
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/storage/pyfs.py", line 73, in open
    fs, path = self._get_fs()
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/invenio_files_rest/storage/pyfs.py", line 64, in _get_fs
    opener.opendir(filedir, writeable=True, create_dir=create_dir),
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/opener.py", line 297, in opendir
    fs, path = self.parse(fs_url, writeable=writeable, create_dir=create_dir)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/opener.py", line 236, in parse
    fs, fs_path = opener.get_fs(self, fs_name, fs_name_params, fs_url, writeable, create_dir)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/opener.py", line 348, in get_fs
    _os_makedirs(path)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/osfs/__init__.py", line 73, in _os_makedirs
    _os_makedirs(head, mode)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/osfs/__init__.py", line 73, in _os_makedirs
    _os_makedirs(head, mode)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/osfs/__init__.py", line 73, in _os_makedirs
    _os_makedirs(head, mode)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/osfs/__init__.py", line 73, in _os_makedirs
    _os_makedirs(head, mode)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/osfs/__init__.py", line 73, in _os_makedirs
    _os_makedirs(head, mode)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/errors.py", line 257, in wrapper
    return func(self,*args,**kwds)
  File "/home/jannis/Envs/zenodo/lib/python2.7/site-packages/fs/osfs/__init__.py", line 79, in _os_makedirs
    os.mkdir(name, mode)
PermissionDeniedError: Unable to _os_makedirs: permission denied

### Things @nuest and I tried without success:
Manipulating the configuration via an invenio.cfg file stored in the virtualenv `var/instance/invenio.cfg`:
1. We changed the FIXTURES_FILES_LOCATION to '/tmp'
2. We changed the FIXTURES_FILES_LOCATION to ''/home/jannis/Envs/zenodo/var/instance/data'
3. We changed the ARCHIVES_FILES_LOCATION to '/home/jannis/Envs/zenodo/var/instance/archive'
4. We changed the access rights of 'home/jannis/Envs/zenodo/var/instance/data' with umask.

Do you have any ideas for which directory I don't have permission?

**Comment by slint** [comment]
I would make sure directories have the correct user/group (via `chmod -R jannis:jannis /home/jannis/Envs/zenodo/var`) w.r.t the user running the `zenodo run` command (also no `sudo ...` should be required/used for any of the commands in the installation guide). 

Other than that I can't see any other obvious cause, the traceback seems pretty standard for a development setup.
