### ISSUE TITLE
Cannot get Zenodo started

### ISSUE THREAD

**Issue by rontrompert** [zenodo/zenodo#2156]
Browser & OS (see also https://www.whatismybrowser.com/): <Browser>:<OS>

## Describe the bug
I have followed the recipe at https://zenodo.readthedocs.io/en/latest/installation.html for the docker installation. 

After building everything using:
$ cd ~/src/
$ git clone https://github.com/zenodo/zenodo.git
$ cd ~/src/zenodo
$ git checkout master
$ docker-compose -f docker-compose.full.yml build
$ docker-compose -f docker-compose.full.yml up -d

$ docker-compose -f docker-compose.full.yml run --rm web bash /code/zenodo/scripts/init.sh

fails with the following stakc trace.

/usr/local/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/base.py:2451: SADeprecationWarning: The create_engine.convert_unicode parameter and corresponding dialect-level parameters are deprecated, and will be removed in a future release.  Modern DBAPIs support Python Unicode natively and this parameter is unnecessary.
  default.DefaultDialect.__init__(self, **kwargs)

/usr/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:157: SADeprecationWarning: Use .persist_selectable
  info = getattr(mapper.mapped_table, 'info', {})

Traceback (most recent call last):
  File "/usr/local/bin/zenodo", line 11, in <module>
    load_entry_point('zenodo', 'console_scripts', 'zenodo')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 419, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/code/zenodo/zenodo/modules/fixtures/cli.py", line 61, in init
    loadbuckets()
  File "/code/zenodo/zenodo/modules/fixtures/files.py", line 42, in loadbuckets
    initialize_exporter_bucket()
  File "/code/zenodo/zenodo/modules/exporter/utils.py", line 45, in initialize_exporter_bucket
    bucket_id))
invenio_files_rest.errors.FilesException: 500 Internal Server Error: None

## Steps to Reproduce
$ cd ~/src/
$ git clone https://github.com/zenodo/zenodo.git
$ cd ~/src/zenodo
$ git checkout master
$ docker-compose -f docker-compose.full.yml build
$ docker-compose -f docker-compose.full.yml up -d

$ docker-compose -f docker-compose.full.yml run --rm web bash /code/zenodo/scripts/init.sh

## Expected behavior
Zenodo website is accessible.

**Comment by VlastaAIP** [comment]
Getting same error and also this one:

```
Indexing records...
Traceback (most recent call last):
  File "/usr/local/bin/zenodo", line 11, in <module>
    load_entry_point('zenodo==3.0.0.dev20150000', 'console_scripts', 'zenodo')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 419, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/invenio_indexer/cli.py", line 63, in run
    es_bulk_kwargs={'raise_on_error': raise_on_error})
  File "/usr/local/lib/python2.7/site-packages/invenio_indexer/api.py", line 210, in process_bulk_queue
    **es_bulk_kwargs
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/actions.py", line 300, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/actions.py", line 230, in streaming_bulk
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/actions.py", line 116, in _process_bulk_chunk
    raise e
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fc2a9bdebd0>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fc2a9bdebd0>: Failed to establish a new connection: [Errno -2] Name or service not known)
ERROR: 1
```
