### ISSUE TITLE
utils: remove_file CLI command still has UTF-8 issues 

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#2158]

**Comment by ctrl-alt-soneca** [comment]
`'ascii' codec can't encode character u'\u0301' in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/zenodo/lib/python2.7/site-packages/raven/utils/serializer/manager.py", line 76, in transform
    return repr(value)
  File "/opt/zenodo/lib/python2.7/site-packages/invenio_files_rest/models.py", line 903, in __repr__
    self.bucket_id, self.key, self.version_id)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 11: ordinal not in range(128)
Traceback (most recent call last):
  File "/opt/zenodo/bin/zenodo", line 11, in <module>
    load_entry_point('zenodo', 'console_scripts', 'zenodo')()
  File "/opt/zenodo/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/zenodo/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zenodo/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/zenodo/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/zenodo/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/flask/cli.py", line 419, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/zenodo/src/zenodo/zenodo/modules/utils/cli.py", line 159, in remove_file
    key=key.decode('utf-8'),
  File "/opt/zenodo/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 11: ordinal not in range(128)`
