### ISSUE TITLE
oai-pmh: ListSets fails with 500 code

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#2265]
Running the following snippet to harvest the `ListSets` OAI-PMH verb fails with a 500

```python
In [1]: import sickle
In [2]: client = sickle.Sickle('https://zenodo.org/oai2d')
In [4]: all_sets = list(client.ListSets())
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)

...

HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://zenodo.org/oai2d?verb=ListSets&resumptionToken=eyJzZWVkIjowLjUyNzg1MzU0Nzg5NjEyNiwicGFnZSI6NDcsImt3YXJncyI6e319.YccFqQ._ZEdN8jpyubCYRUcuMypfm28WQU
```

---

Had a further look into it and apparently, it's an invalid XML characters issue:

```python
[2021-12-29 12:01:18,831] ERROR in app: Exception on /oai2d [GET]
Traceback (most recent call last):
  File "/opt/zenodo/lib/python2.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/zenodo/lib/python2.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/zenodo/lib/python2.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/zenodo/lib/python2.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/zenodo/lib/python2.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/zenodo/lib/python2.7/site-packages/webargs/core.py", line 452, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/invenio_oaiserver/views/server.py", line 84, in response
    e_tree = getattr(xml, args['verb'].lower())(**args)
  File "/opt/zenodo/lib/python2.7/site-packages/invenio_oaiserver/response.py", line 209, in listsets
    e_description.text = oai_set.description
  File "src/lxml/etree.pyx", line 1024, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

So some community has a description that includes "NULL bytes or control characters".

**Comment by slint** [comment]
Fix published for `invenio-oaiserver` at https://github.com/inveniosoftware/invenio-oaiserver/pull/205. `Invenio-OAIServer v1.1.1.post1` released on PyPI with backport: https://pypi.org/project/invenio-oaiserver/1.1.1.post1/. 

All that's left is:

- [ ] Tests to pass to merge https://github.com/zenodo/zenodo/pull/2270
- [ ] Deploy Sandbox
  - [ ] Iterate through all of ListSets
- [ ] Deploy Prod
   - [ ] Iterate through all of ListSets
