### ISSUE TITLE
Impossible to upload my dataset because your server is ALWAYS resetting connections before end of upload !

### ISSUE THREAD

**Issue by jarredou** [zenodo/zenodo#2514]
Impossible to share my dataset with the community because your server is ALWAYS resetting connection before end upload.
UI and API are failing the same way.

```
Traceback (most recent call last):
  File "D:\!Dev\zenodo.py", line 42, in <module>
    r = requests.put(
  File "C:\Program Files\Python38\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python38\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))
```

**Comment by carlinmack** [comment]
Very sorry to hear you are having problems, What is the size of your upload? We are seeing users having difficulties with archives greater than 8GB

**Comment by mjfos2r** [comment]
to add to this, I am also struggling to download large datasets due to the same connection issue. My file is 40gb.

**Comment by Raen111** [comment]
[>](url) to add to this, I am also struggling to download large datasets due to the same connection issue. My file is 40gb.

**Comment by fburic** [comment]
I believe this is some sort of timeout issue. 

I was experiencing upload errors using the Web interface with a 9.2 GB file (on Firefox 122, NetworkError without details in the Javascript console after the progress bar turned red).

My upload speed was 10 Mbps and the upload would halt at about 30-50%, after 40-50? minutes.
I switched to a 100 Mbps upload plan and the upload finished without a problem and of course, at a much higher speed. I didn't time it but it felt like x10 increase, as expected (was done in ~15 min), meaning I likely haven't hit whatever upload limit Zenodo has.

So it seems to me that the time needed for uploading might be the factor setting off the connection resets.
I naturally cannot account for Zenodo server load, so no idea how that plays into it. The upload speed on the 10 Mbps connection wasn't constant between attempts.

Hope this helps.

**Comment by AgilentGCMS** [comment]
Came here to say that I've tried all day to upload a 4.4 GB file using the web interface, but each time it gets stuck at a random point, usually in the 30-40% range. My upload speed, as tested by Ookla, is 300 Mbps, so that can't be the limiting cause.

**Comment by santaep** [comment]
> Came here to say that I've tried all day to upload a 4.4 GB file using the web interface, but each time it gets stuck at a random point, usually in the 30-40% range. My upload speed, as tested by Ookla, is 300 Mbps, so that can't be the limiting cause.

same for me :/ files size is around 8GB

**Comment by Chobbes** [comment]
Getting reports of this happening for artifact uploads as well that are around ~8gb in size.

**Comment by AgilentGCMS** [comment]
I had filed a [separate report](#2582) on this, but that was closed by @slint with a canned response about the 50 GB quota. I gave up and split my archive into 1 GB or less chunks. I don't expect this to be solved anytime soon.

**Comment by stevenb21** [comment]
Hello, I am also having headaches with the html upload. I am uploading a single ~4GB file at a time and it's a 50/50 shot it goes through.

I noticed when my computer locks, the html fails as well. My work around for that is having a 12 hour youtube video playing.

Despite the cute youtube work around, the html upload fails still.

Hope this gets fixed soon.

**Comment by na3103** [comment]
I have about 40GB of data to upload, and I've already split it into ~20 files of sizes varying from 400MB-4GB. Files on the MB scale can take at least an hour to upload, and for anything larger than a few GB's, I have to leave it running overnight (which is just not scalable). Zenodo is being *incredibly* slow with uploads, and is really blocking my research.

Is there any possible workaround, or a timeline for fixing this? Uploading via curl and Python also doesn't seem to be faring much better.

**Comment by EPronizius** [comment]
Same here. Sometimes Zenodo stops uploading at a random percentage and then does nothing. It doesn’t even turn red. I waited for over an hour for it to move from 77% to 78%, but nothing happened.  I had to cancel one today that was stuck at 89% — it was a pain (5 GB! file).

**Comment by samotracio** [comment]
Same issue here. Uploading just ~180MB files though 300Mbit connection (web interface). Random stops and painfully slow, even when uploading files one by one. Any solution for this?

**Comment by enrico-mi** [comment]
Same. I've been trying to upload a 9.3 GB zip file for the past 6 hours with no luck. I tried again and it is now at around 5% after an hour: this means an upload speed of 0.13 Mbit/s when my connection upload speed is actually 27 Mbit/s. At this rate, it's going to take 20 hrs to upload 9 GB?! Both web interface and API gives the same performance

**Comment by romanovzky** [comment]
Same here, a couple of 4gb files, some 2gb, and a few under 500mb. Can't upload via web nor API.

**Comment by yaxu** [comment]
I'm also having problems uploading files around 500MB - very slow, with resets requiring multiple attempts.
This seems to have been the case for five years #2087

**Comment by tensional** [comment]
Same here, the frozen upload whilst still displaying the web page (as blue in progress, unchanged) is VERY annoying. Please sort out a clear troubleshooting for uploads between 2-6 GB!

**Comment by MOS0206** [comment]
Same here, I wanted to upload a 120 Gb data set and feels an impossible task; unlucky I will have to find alternatives.
Any idea?

**Comment by Bra1nsen** [comment]
Really useless, tried now 3 times to upload 48GB file, and always gets stuck

<img width="1314" height="446" alt="Image" src="https://github.com/user-attachments/assets/eb96a3c1-b303-44eb-9709-09481ec8a87b" />

**Comment by romanovzky** [comment]
So, this is not a fix, but it's a temporary solution. I've been able to upload with good speeds if I connect with a VPN to Switzerland. This suggests to me that Zenodo is soft-blocking some DNS or ISP providers.

**Comment by slint** [comment]
I'm closing this issue since this repo isn't really set up for user support. Please use https://zenodo.org/support where we can actually help troubleshoot this kind of issues.

I do want to address something that's come up a few times here: we don't block or deprioritize any IPs, ISPs, or regions. The only time we block at the IP or User-Agent level is temporarily during DDoS attacks. Our infrastructure is in Geneva, Switzerland, and over the years we've troubleshooted connection issues with users all over the world to balance stability and speed. These configurations are always a compromise, and we know that some users will have worse experiences than others depending on their location and ISP.

We're currently seeing on average 20-35TB uploaded per month consistently for the past 3 years, which means that uploads are generally working for users. I understand this doesn't help much if yours specifically isn't working, and we're sorry about that.

On the technical side, we're working with other research institutions and infrastructures on enabling server-to-server transfers that can run in the background, which should help for cases where a user's local connection is the bottleneck.

We're also looking at resumable uploads so that if something fails partway through, you don't lose all progress. That one's tricky for us because our storage layer at CERN is optimized for streaming whole large files, with the assumption of large timeouts (2min+) and high latency, so chunked uploads add overhead we need to work around.

In the meantime, if you're comfortable with scripting, using our REST API with longer timeouts on your HTTP client can help with large file uploads over slower or less stable connections.

If you're still having issues, please reach out via https://zenodo.org/support with details and we'll see what we can figure out.

**Comment by yaxu** [comment]
Thanks for the response, I was already using the REST API, using python requests library which doesn't timeout by default. I've finally uploaded my files now so don't need support.

**Comment by tensional** [comment]
> I'm closing this issue since this repo isn't really set up for user support. Please use https://zenodo.org/support where we can actually help troubleshoot this kind of issues.
> 
> I do want to address something that's come up a few times here: we don't block or deprioritize any IPs, ISPs, or regions. The only time we block at the IP or User-Agent level is temporarily during DDoS attacks. Our infrastructure is in Geneva, Switzerland, and over the years we've troubleshooted connection issues with users all over the world to balance stability and speed. These configurations are always a compromise, and we know that some users will have worse experiences than others depending on their location and ISP.
> 
> We're currently seeing on average 20-35TB uploaded per month consistently for the past 3 years, which means that uploads are generally working for users. I understand this doesn't help much if yours specifically isn't working, and we're sorry about that.
> 
> On the technical side, we're working with other research institutions and infrastructures on enabling server-to-server transfers that can run in the background, which should help for cases where a user's local connection is the bottleneck.
> 
> We're also looking at resumable uploads so that if something fails partway through, you don't lose all progress. That one's tricky for us because our storage layer at CERN is optimized for streaming whole large files, with the assumption of large timeouts (2min+) and high latency, so chunked uploads add overhead we need to work around.
> 
> In the meantime, if you're comfortable with scripting, using our REST API with longer timeouts on your HTTP client can help with large file uploads over slower or less stable connections.
> 
> If you're still having issues, please reach out via https://zenodo.org/support with details and we'll see what we can figure out.

So you made this repo with the aforementioned title yet it wasn't intended for support? In addition, stating Zenodo uploads 30TB per month means nothing without how much data was attempted to be uploaded for comparison. That's all I have to say.

Best wishes,

Tension

**Comment by tensional** [comment]
Back again and to my amazement, this problem seems to be even worse! Currently on 4th attempt trying to upload a 200MB compressed file. Who knew trying to upload ~half a GB online should take all day...

**Comment by pranavdurai10** [comment]
I've been having the same issue. I'm uploading two datasets as two individual publications. 

The first one was just 1.89GB, so it uploaded successfully. However, the second dataset is ~12GB, and it failed multiple times during upload. 

Was anyone successful using the REST API method that @slint suggested?

**Comment by pranavdurai10** [comment]
## Update: 13.07.2026 - Issue Resolved! 

Both browser upload and Python requests-based REST API uploads failed repeatedly with:

`SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2436)'))`

The Python script would progress to ~52% on the best attempt before the connection reset, always starting from 0% on retry since Zenodo doesn't support resumable uploads.

What worked: Spinning up a cloud compute instance in Norway (Vast.ai, 5967 Mbps download / 8272 Mbps upload) and running the REST API upload from there. The Norway to Geneva datacenter routing completed the full 11.77 GB upload in ~20 minutes with no connection resets whatsoever. My home connection failed every time regardless of approach.

Key insight: This confirms the earlier suggestion in this thread about Swiss / European VPN routing, and the issue is specifically with long-distance home connections to Zenodo's Geneva servers timing out during large uploads. A European datacenter connection with strong upload bandwidth bypasses the SSL timeout entirely.

For others hitting this: If you have access to any cloud compute in Europe (AWS eu-west, GCP europe-west, Vast.ai European instances etc.), uploading from there rather than your home connection will resolve the SSL EOF issue for really large files. The closer geographically to Geneva the better, and Norway worked perfectly for me.

REST API upload script that handles retries and MD5 verification (drop-in, works with any Zenodo draft record):

```python
"""
Code written by Pranav Durai on 12.07.2026

zenodo_upload.py — Upload a large file to Zenodo via REST API.

Handles large files reliably with configurable timeouts and retry logic,
avoiding the browser-based connection reset issues with files > 5GB.

Usage:
    python zenodo_upload.py \
        --token YOUR_ZENODO_API_TOKEN \
        --file  msl-boulder-dataset.zip \
        --record-id 1234567                     # optional: existing draft record ID
                                                # omit to create a new draft

Requirements:
    pip install requests tqdm
"""

import argparse
import hashlib
import sys
import time
from pathlib import Path

import requests
from tqdm import tqdm

# Configurations
BASE_URL    = "https://zenodo.org/api"
CHUNK_SIZE  = 8 * 1024 * 1024                   # 8 MB read buffer for MD5 + progress
TIMEOUT     = (30, 7200)                        # (connect timeout, read timeout) in seconds
MAX_RETRIES = 5
RETRY_DELAY = 10                                # seconds between retries


# Helpers
def md5(file_path: Path) -> str:
    """
    Compute MD5 checksum of a file.
    """
    h = hashlib.md5()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(CHUNK_SIZE), b""):
            h.update(chunk)
    return h.hexdigest()


def get_headers(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }


# Zenodo API calls
def create_draft(token: str) -> str:
    """
    Create a new empty draft deposit and return its record ID.
    """
    r = requests.post(
        f"{BASE_URL}/deposit/depositions",
        json={},
        headers=get_headers(token),
        timeout=TIMEOUT,
    )
    r.raise_for_status()
    record_id = str(r.json()["id"])
    print(f"Created new draft record: {record_id}")
    return record_id


def get_bucket_url(token: str, record_id: str) -> str:
    """Retrieve the S3-like bucket URL for a draft record."""
    r = requests.get(
        f"{BASE_URL}/deposit/depositions/{record_id}",
        headers=get_headers(token),
        timeout=TIMEOUT,
    )
    r.raise_for_status()
    bucket_url = r.json()["links"]["bucket"]
    print(f"Bucket URL: {bucket_url}")
    return bucket_url


def upload_file(token: str, bucket_url: str, file_path: Path) -> dict:
    """
    Upload a file to Zenodo's S3 bucket endpoint with progress bar and retries.
    Returns the file metadata dict from Zenodo on success.
    """
    file_size = file_path.stat().st_size
    filename  = file_path.name

    print(f"\nUploading: {filename} ({file_size / 1e9:.2f} GB)")
    print(f"Computing MD5 checksum...")
    local_md5 = md5(file_path)
    print(f"MD5: {local_md5}")

    upload_url = f"{bucket_url}/{filename}"

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"\nAttempt {attempt}/{MAX_RETRIES}...")
        try:
            with open(file_path, "rb") as f:
                with tqdm(
                    total=file_size,
                    unit="B",
                    unit_scale=True,
                    unit_divisor=1024,
                    desc=filename,
                ) as pbar:

                    class ProgressReader:
                        def __init__(self, fobj):
                            self.fobj = fobj

                        def read(self, size=-1):
                            chunk = self.fobj.read(size)
                            pbar.update(len(chunk))
                            return chunk

                    response = requests.put(
                        upload_url,
                        data=ProgressReader(f),
                        headers={
                            "Authorization": f"Bearer {token}",
                            "Content-Type": "application/octet-stream",
                            "Content-Length": str(file_size),
                        },
                        timeout=TIMEOUT,
                    )
                    response.raise_for_status()

            # Verify checksum
            remote_md5 = response.json().get("checksum", "").replace("md5:", "")
            if remote_md5 and remote_md5 != local_md5:
                print(f"Checksum mismatch! Local: {local_md5}, Remote: {remote_md5}")
                raise ValueError("Checksum mismatch after upload.")

            print(f"\nUpload successful.")
            print(f"Local MD5 : {local_md5}")
            print(f"Remote MD5: {remote_md5}")
            return response.json()

        except (requests.exceptions.ConnectionError,
                requests.exceptions.Timeout,
                requests.exceptions.ChunkedEncodingError,
                ValueError) as e:
            print(f"Attempt {attempt} failed: {e}")
            if attempt < MAX_RETRIES:
                print(f"Retrying in {RETRY_DELAY}s...")
                time.sleep(RETRY_DELAY)
            else:
                print("All retry attempts exhausted.")
                raise

    return {}


# Main
def main():
    parser = argparse.ArgumentParser(
        description="Upload a large file to Zenodo via REST API.")
    parser.add_argument("--token", required=True,
                        help="Zenodo API token (deposit:write scope)")
    parser.add_argument("--file", required=True,
                        help="Path to the file to upload")
    parser.add_argument("--record-id", default=None,
                        help="Existing draft record ID (omit to create new)")
    args = parser.parse_args()

    file_path = Path(args.file)
    if not file_path.exists():
        print(f"Error: file not found — {file_path}", file=sys.stderr)
        sys.exit(1)

    token = args.token

    # Get or create draft record
    if args.record_id:
        record_id = args.record_id
        print(f"Using existing draft record: {record_id}")
    else:
        record_id = create_draft(token)

    # Get bucket URL
    bucket_url = get_bucket_url(token, record_id)

    # Upload file
    result = upload_file(token, bucket_url, file_path)

    print("\n" + "=" * 60)
    print(f"Done!")
    print(f"Record ID : {record_id}")
    print(f"Record URL: https://zenodo.org/deposit/{record_id}")
    print("Fill in the metadata on Zenodo and hit Publish when ready.")
    print("=" * 60)


if __name__ == "__main__":
    main()
```

Usage:

```bash
# Library requirements
pip install requests tqdm

# With existing draft record
python zenodo_upload.py \
    --token YOUR_ZENODO_API_TOKEN \
    --file your-dataset.zip \
    --record-id YOUR_RECORD_ID

# Or create a new draft automatically
python zenodo_upload.py \
    --token YOUR_ZENODO_API_TOKEN \
    --file your-dataset.zip
```

Get your API token at `zenodo.org/account/settings/applications/tokens/new/` with `deposit:write` scope. Your record ID is the number in the URL at `zenodo.org/deposit/XXXXXXX`.

**Comment by sammlapp** [comment]
Thanks for sharing... but what if we don't have access to European cloud instances?

**Comment by pranavdurai10** [comment]
@sammlapp - use a VPN.

**Comment by sammlapp** [comment]
VPN didn't help much - but I was able to get my data uploaded by sharding into 1 Gb files (which makes it annoying to start using the dataset, requiring running a script to put the data back together)
