### ISSUE TITLE
500 error trying to upload new version from gitlab via API using gitlab2zenodo

### ISSUE THREAD

**Issue by kratsg** [zenodo/zenodo#2543]
Package: https://gitlab.com/sbeniamine/gitlab2zenodo/

```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
id
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
links
INFO:root:new version
INFO:root:clean
INFO:root:upload metadata
Traceback (most recent call last):
  File "/Users/kratsg/combiner/venv/bin/g2z-send", line 8, in <module>
    sys.exit(g2z_command())
             ^^^^^^^^^^^^^
  File "/Users/kratsg/combiner/venv/lib/python3.11/site-packages/gitlab2zenodo/main.py", line 95, in g2z_command
    send(settings=Settings(args))
  File "/Users/kratsg/combiner/venv/lib/python3.11/site-packages/gitlab2zenodo/deposit.py", line 366, in send
    deposit.upload_metadata({'metadata': metadata})
  File "/Users/kratsg/combiner/venv/lib/python3.11/site-packages/gitlab2zenodo/deposit.py", line 219, in upload_metadata
    r = self._request("PUT", "/" + self._latest_id(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kratsg/combiner/venv/lib/python3.11/site-packages/gitlab2zenodo/deposit.py", line 92, in _request
    raise requests.RequestException(", ".join([f"{k}: {v}" for k, v in r.json().items()]) + details)
requests.exceptions.RequestException: error_id: 074ca62653c54015a327f7f24aab8236, message: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application., status: 500

Occurred while sending PUT to https://zenodo.org/api/deposit/depositions/12014882
```

It would be nice to understand what the issue was here.

**Comment by kratsg** [comment]
the metadata that is trying to be uploaded is:

```json
{
    "title": "Combiner: 0.0.3",
    "doi": "10.5281/zenodo.12007778",
    "publication_date": "2024-06-17",
    "description": "<p>framework to combine different measurements that can have statistical overlap and/or different constraints and pulls of the nuisance parameters</p>",
    "access_right": "open",
    "creators": [
        {
            "name": "Dado, Tomas",
            "affiliation": "European Organization for Nuclear Research",
            "orcid": "0000-0002-7050-2669"
        }
    ],
    "keywords": [
        "physics",
        "statistics",
        "fitting",
        "combination",
        "c++",
        "ROOT"
    ],
    "version": "0.0.3",
    "custom": {
        "code:codeRepository": "https://gitlab.cern.ch/tdado/combiner/-/tags/v0.0.3",
        "code:programmingLanguage": [
            {
                "id": "c++",
                "title": {
                    "en": "C++"
                }
            }
        ],
        "code:developmentStatus": {
            "id": "active",
            "title": {
                "en": "Active"
            }
        }
    },
    "license": "apache2.0",
    "imprint_publisher": "Zenodo",
    "upload_type": "software",
    "prereserve_doi": {
        "doi": "10.5281/zenodo.12007778",
        "recid": 12007778
    }
}
```

**Comment by carlinmack** [comment]
if you wrap this in a `metadata` object it works for me:

```python
{
  "metadata": {
    "title": "Combiner: 0.0.3",
    "doi": "10.5281/zenodo.12007778",
    "publication_date": "2024-06-17",
    "description": "<p>framework to combine different measurements that can have statistical overlap and/or different constraints and pulls of the nuisance parameters</p>",
    "access_right": "open",
    "creators": [
        {
            "name": "Dado, Tomas",
            "affiliation": "European Organization for Nuclear Research",
            "orcid": "0000-0002-7050-2669"
        }
    ],
    "keywords": [
        "physics",
        "statistics",
        "fitting",
        "combination",
        "c++",
        "ROOT"
    ],
    "version": "0.0.3",
    "custom": {
        "code:codeRepository": "https://gitlab.cern.ch/tdado/combiner/-/tags/v0.0.3",
        "code:programmingLanguage": [
            {
                "id": "c++",
                "title": {
                    "en": "C++"
                }
            }
        ],
        "code:developmentStatus": {
            "id": "active",
            "title": {
                "en": "Active"
            }
        }
    },
    "license": "apache2.0",
    "imprint_publisher": "Zenodo",
    "upload_type": "software",
    "prereserve_doi": {
        "doi": "10.5281/zenodo.12007778",
        "recid": 12007778
    }
}
}
```

**Comment by carlinmack** [comment]
reopen if there's still an issue :)

**Comment by kratsg** [comment]
Got it, that was not necessarily obvious! Would have been nicer to have something better than 500 error.

**Comment by carlinmack** [comment]
fair, I receive a 400 with your metadata using https://usebruno.com but unsure how you are making the request
<img width="1133" alt="image" src="https://github.com/zenodo/zenodo/assets/6676843/c8c6da4b-6136-463a-ae75-71548025e9af">

**Comment by kratsg** [comment]
I am using https://gitlab.com/sbeniamine/gitlab2zenodo (HEAD of the main branch). Now, after fixing the metadata, I have

```
$ git archive --format zip --output ${CI_COMMIT_TAG#v}.zip ${CI_COMMIT_TAG}
$ g2z-send -i $zenodo_record -t $zenodo_token -s -m .zenodo.json ${CI_COMMIT_TAG#v}.zip
INFO:root:Getting the ID for the latest version of the concept
Traceback (most recent call last):
  File "/usr/local/bin/g2z-send", line 8, in <module>
    sys.exit(g2z_command())
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gitlab2zenodo/main.py", line 95, in g2z_command
    send(settings=Settings(args))
  File "/usr/local/lib/python3.11/site-packages/gitlab2zenodo/deposit.py", line 355, in send
    deposit.get_deposit(record)
  File "/usr/local/lib/python3.11/site-packages/gitlab2zenodo/deposit.py", line 124, in get_deposit
    api_ret = self._request(
              ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gitlab2zenodo/deposit.py", line 92, in _request
    raise requests.RequestException(", ".join([f"{k}: {v}" for k, v in r.json().items()]) + details)
requests.exceptions.RequestException: status: 403, message: Permission denied.
Occurred while sending GET to https://sandbox.zenodo.org/api/deposit/depositions
```

So I think this is progress and I need to dig into the way I'm authenticating with the API.
