### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by k3njiy** [zenodo/zenodo#459]
Following the steps in INSTALL.rst results in following error when issuing the command 
`docker-compose run web zenodo db create` thus making Zenodo not installable at the moment using the docker method.
```
Traceback (most recent call last):
  File "/usr/local/bin/zenodo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3140, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3153, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 828, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zenodo' distribution was not found and is required by the application
```

**Comment by lnielsen** [comment]
We are in the middle of big rewrite so install will be in flux until we've launched.

**Comment by k3njiy** [comment]
Thank you for the answer. Didn't know that Zenodo is also undergoing the migration.
