### ISSUE TITLE
Error loading demo records

### ISSUE THREAD

**Issue by nuest** [zenodo/zenodo#623]
I'm trying to run a local Zenodo set-up following these instructions: http://zenodo.readthedocs.io/installation.html#docker-installation

Everything seems to work fine until "load demo records":

```
~/git/zenodo$ docker-compose run –rm web zenodo fixtures loaddemorecords
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/compose/cli/main.py", line 55, in main
  File "/code/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/code/compose/cli/docopt_command.py", line 26, in dispatch
  File "/code/compose/cli/main.py", line 174, in perform_command
  File "/code/compose/cli/main.py", line 459, in run
  File "/code/compose/project.py", line 113, in get_service
  File "/code/compose/project.py", line 414, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
docker-compose returned -1
:~/git/zenodo$ docker-compose run –rm web zenodo fixtures loaddemorecords
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/compose/cli/main.py", line 55, in main
  File "/code/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/code/compose/cli/docopt_command.py", line 26, in dispatch
  File "/code/compose/cli/main.py", line 174, in perform_command
  File "/code/compose/cli/main.py", line 459, in run
  File "/code/compose/project.py", line 113, in get_service
  File "/code/compose/project.py", line 414, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
docker-compose returned -1
~/git/zenodo$ docker-compose run –rm web zenodo migration recordsrun
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/compose/cli/main.py", line 55, in main
  File "/code/compose/cli/docopt_command.py", line 23, in sys_dispatch
  File "/code/compose/cli/docopt_command.py", line 26, in dispatch
  File "/code/compose/cli/main.py", line 174, in perform_command
  File "/code/compose/cli/main.py", line 459, in run
  File "/code/compose/project.py", line 113, in get_service
  File "/code/compose/project.py", line 414, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
docker-compose returned -1
```

I'm running Ubuntu 16.04.

Any ideas or hints how to fix this? Thanks!

**Comment by lnielsen** [comment]
Thanks for reporting the issue. We'll check it. Normally we have it working on both OS X and Ubuntu, but we primarily use a local development installation as it's usually faster (see https://github.com/zenodo/zenodo/blob/master/docs/installation.rst). We are pushing towards a new release soon, so it might also be that there's just issue with demo records. Last but not least, it could just be docker + docker compose - they evolve so fast it's hard to keep track.

**Comment by nuest** [comment]
Good points. Let me know if I can try sth. out. For the sake of completeness:

```
$ docker --version
Docker version 1.11.2, build b9f10c9
$ docker-compose --version
docker-compose version 1.6.0, build d99cad6
```
