### ISSUE TITLE
celery: checksum calculation fails

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#814]
```
Traceback (most recent call last):
  File "/opt/zenodo/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/flask_celeryext/app.py", line 43, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/zenodo/lib/python2.7/site-packages/invenio_files_rest/tasks.py", line 59, in verify_checksum
    f.verify_checksum(progress_callback=progress_updater)
  File "/opt/zenodo/lib/python2.7/site-packages/invenio_files_rest/models.py", line 673, in verify_checksum
    progress_callback=progress_callback)
  File "/opt/zenodo/lib/python2.7/site-packages/invenio_xrootd/storage.py", line 85, in checksum
    algo, val = fs.xrd_checksum(path)
AttributeError: 'OSFS' object has no attribute 'xrd_checksum'
```

**Comment by lnielsen** [comment]
Fixed
